= Decentralized Payment Systems Economics
Giulia Fanti, CMU;  Leonid Kogan, MIT;  Sewoong Oh, UW Seattle;  Pramod Viswanath, UIUC
:toc:
:toclevels: 4

== Beginning

> The economic properties of cryptocurrencies are of central interest to a payment system and the focus of this chapter. Economic properties are closely intertwined with the specifics of the system design; this is particularly true for proof-of-stake (PoS) cryptocurrencies. In this chapter, we focus on three broad and connected issues related to the design of Unit-e: (i) valuation of cryptocurrencies in the proof-of-stake setting, (ii) the selection of block rewards, and (iii) the selection and disbursal of transaction fees. In particular, we highlight the delicate connection between these issues and our overall design of Unit-e as a proof-of-stake (PoS) payment system.  +

加密货币的经济属性是一个支付系统的核心利益，也是本章的重点。 经济属性与支付系统设计的细节密切相关，对于使用权益证明（PoS）机制的加密货币尤其如此。在本章中，我们着重讨论与 Unit-e 设计相关的三个普遍而紧密相连的问题：**（i）使用权益证明（PoS）机制的加密货币的估值问题**，**（ii）区块奖励选择问题**，以及**（iii）交易费用的选择和支付问题**。 尤其是，Unit-e 作为一个权益证明（PoS）机制下的支付系统，我们要特别强调这些问题与 Unit-e 整体设计之间的细微联系。 +
_注：Unit-e，是要给专注于支付的加密货币，是由分布式技术研究基金会支持的一个高度可扩展的、完全分布式的支付系统。_

> This chapter has three contributions:  +

这篇文章有三个贡献：

> 1.  We present a theoretical valuation framework for PoS payment systems. Although cryptocurrencies can have applications beyond just payment processing, this framework gives us a concrete lower bound for reasoning about the fiat valuation of Unit-e. Unlike PoW cryptocurrencies, the first-order eﬀect is no longer the cost of keeping the network running (i.e., mining). Instead, token valuation stems from a combination of two factors: consumer demand for holding tokens, and validator demand for holding tokens. The first term is inversely proportional to token velocity, whereas the second term is proportional to the economic value of the aggregate transaction fee flow. Our analysis provides an important input into various design decisions in PoS systems, including monetary policy, rewards, transaction fees, and network security mechanisms.  +
>
> 2. We study the effects of block rewards on user adoption and equity of rewards among block proposers and validators. One key insight is that in PoS systems, severe stake imbalance can arise from compounding in users’ stake pools, even if nodes are following protocol. That is, a node that starts with a small fraction of stake can end up with an arbitrarily high fraction of stake, simply due to randomness in the PoS proposal stage. We show theoretically that this eﬀect can be mitigated through two factors: choice of block reward function and size of the initial stake pool. We prove the optimality (in terms of maximizing equitability) of a novel **geometric block reward function** and advocate for starting with a large initial stake pool to mitigate the eﬀects of stake compounding.  +
>
> 3. We discuss various transaction fee mechanisms, highlighting key tradeoﬀs of various design choices in terms of supporting low congestion and stable valuations according to the models in part (1).   +

1. 我们提出了一个PoS支付系统的估值架构。虽然加密货币的应用不仅仅局限于支付的处理，但这个框架为我们提供了一个具体的下限，用于对e单元（Unit-e）进行法定估值推理。与PoW加密货币不同，一阶效应不再是维持网络运转（即挖矿）的成本。相反，代币估值源于两个因素的组合：消费者持有代币的需求和验证者持有代币的需求。第一项与代币的周转率成反比，而第二项与总交易费用流的经济价值成正比。我们的分析为POS系统的各种设计决策提供了重要的输入，包括货币政策、奖励、交易费用和网络安全机制。  +

2. 我们研究了区块奖励对用户采用情况的影响，以及奖励的公平性在出块人和验证人之间的影响。一个关键的领悟是，在 PoS 系统中，即使节点遵守协议，用户权益池中的复利也可能引起严重的权益失衡。也就是说，一个只是以很小的权益开始的节点，最终可能获得一个任意高比例的权益，而这仅仅是由于 PoS 提案阶段的随机性所致。我们从理论上证明，这种影响可以通过两个因素来减轻：区块奖励函数的选择、初始权益池的大小。我们证明了一个新奇的**几何区块奖励函数**在公平性最大化方面的最优性，并提倡从一个大的初始权益池开始，以减轻权益复利的影响。   +

3. 根据论文第（1）部分的模型，我们论述了各种交易费用机制，着重强调了各种设计选择在支持低拥堵和稳定估值方面的关键权衡。  +

> We want to emphasize that valuation and incentive mechanisms are closely intertwined. Incentive mechanisms play a dual role in the payment network: they elicit “good” behavior from network participants, such as block validators; they also distribute rewards, thereby aﬀecting the allocation of tokens and the overall valuation. Our focus here is on the second aspect. Because tokens can be easily re-allocated across the network, they must earn the same rate of return regardless of how they are used. This implies that a system’s choice of incentive mechanisms in relation to any particular activity (e.g., block validation, or oﬀ-chain transaction routing) potentially aﬀects the entire system through its eﬀect on token valuation. For example, suppose one were to increase rewards for block validation: each token staked would now earn a higher expected number of tokens per unit of time as a reward. This would attract tokens towards validation and away from other activities, e.g., from oﬀ-chain transaction routing. The result would be increased congestion for on-chain transactions, and lower transaction volume of oﬀ-chain transactions. Another implication could be a reduction in the rate of growth of the token price, which would act to oﬀset the increased level of rewards for validation in terms of tokens. This, in turn, would make it more costly to hold tokens for transaction purposes. As this informal argument highlights, it is critical to analyze incentive designs in equilibrium, internalizing the eﬀect of each incentive scheme on the entire network.  +

我们要强调的是，**估值和激励机制是紧密相连的**。激励机制在支付网络中扮演着双重角色：他们会引导网络参与者向“善”，比如区块验证者；它们还扮演着分发奖励的角色，从而影响代币的分配和整体估值。这里我们着重关注第二部分。因为代币很容易在整个网络中被重新分配，所以无论他们被如何使用，都必须获得相同的回报率。这意味着，系统中对任何特定活动的激励机制的选择（例如，区块验证、链下交易通道），都会通过对代币估值的影响从而对整个系统产生潜在影响。举个例子，假设一个人为了增加区块验证的奖励：现在，他押入的每一个代币在每个时间单元将获得更高期望值的代币数量作为奖励。这将吸引代币朝着验证聚集，并远离其他活动，例如，从链下交易通道转向去做验证。其结果是增加了链上交易的拥堵，降低了链下交易的交易额。另一层含义可能是降低代币价格的增长率，这表现为抵消了验证奖励的代币所带来的收益增长水平。相应地，这将使持有代币进行交易的成本更高。正如这一非正式的论点所强调的，这对于分析激励设计的均衡性、将每个激励方案在整个网络中的效果进行内化是至关重要的。  +

> More concretely, our primary focus in this chapter will be on incentive mechanisms that encourage participation in block proposal and validation. Participation incentives in cryptocurrencies generally take one of two forms: **(1) transaction fees**, and **(2) validation/block rewards**. Transaction fees are a small fee paid to validators and/or block proposers as a reward for processing a given transaction. In Bitcoin, transaction fees are given to the miner whose block contains the transaction, and are paid by the user who generates the payment. Block rewards, on the other hand, are freshly-minted tokens that are awarded to the node(s) that validate and/or propose a particular block. In some blockchain systems, the roles of block proposers and validators can be separate; for instance, Ethereum proposes such a structure in its future roadmap [183], and Prism naturally separates the functionalities (Chapter 3). In aggregate, transaction fees and block rewards must be valuable enough to incentivize validators to participate in the network. At the same time, transaction fees must be low enough to incentivize participation from transactors. The idea of cryptocurrencies as payment systems has garnered mainstream support based on the premise that transaction fees can be lower relative to traditional services (e.g., credit cards). Thus, at the outset, there exists potential surplus that consumers and network participants aim to realize by reducing transaction frictions. Network participants, like validators, oﬀer services that consume resources and need to be compensated: these services are ultimately compensated with fees paid by consumers. A network design (like Bitcoin) that relies on congestion to induce consumers to oﬀer suﬃciently high fees to support network activities is ineﬃcient: while congestion serves as a part of the revelation mechanism, it imposes dead-weight losses on the entire economic system. From this perspective, a design like the POS system, which instead relies on financial incentives (which are transfers between various actors) is appealing due to its eﬃciency: it better preserves the total consumer surplus.  +

更具体地说，我们在本章中的主要关注点是鼓励参与出块和验证的激励机制。加密货币的参与激励手段通常采用两种形式之一：**（1）交易费用**；**（2）验证/出块奖励**。交易费用是支付给验证者和/或区块提案人的小额费用，作为处理给定交易的奖励。在比特币中，交易费用被支付给了所打包区块中包含该笔交易的矿工，并且是由产生该笔付款的用户支付。另一方面，区块奖励是新“铸造”出来的代币，奖励给验证和/或提案特定区块的节点（单个或多个节点）。在一些区块链系统中，区块的出块者和验证者的角色可能是分开的；例如，以太坊在其未来的路线图[183]中提出了这样的结构，还有，Prism协议也自然而然地分开了这个功能~（Prism协议，一个接近物理极限的共识协议，在本论文第3章给出了详细解说）~。总的来说，交易费用和区块奖励必须具有足够的价值，以激励验证者参与网络。同时，交易费用必须足够低，以激励交易人士的参与。加密货币作为支付系统的理念获得主流支持的前提是交易费用相对于传统服务（如信用卡）可以更低。因此，从一开始，消费者和网络参与者都希望通过减少交易摩擦来赚取潜在的盈余。网络参与者，如验证者，提供一些消耗资源的服务，并且需要得到补偿：这些服务最终由消费者支付的费用来补偿。一个依靠网络拥堵来诱导消费者提供足够高的费用来支持网络活动的区块链网络设计（如比特币）是没有效率的：当拥堵成为启示机制的一部分的时候，它会强加给整个经济系统以沉重的损失。从这个角度来看，像POS系统这样依靠金融激励（在不同参与者之间传输）的设计之所以吸引人，是因为它的效率：它更好地保留了消费者的全部盈余。  +


